jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: oracle
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Build, test (no integration) and Sonarqube analyse
      run: mvn verify -pl '!biojava-integrationtest' org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.projectKey=biojava_biojava -Dsonar.organization=biojava --no-transfer-progress
    strategy:
      fail-fast: false
      matrix:
        java:
        - 21
        os:
        - ubuntu-latest
      max-parallel: 4
name: Master Build
on:
  repository_dispatch:
    types: trigger-ga___master.yml
permissions:
  contents: read
